pep/app/pods/components/modal-dialogs/user/about/component.ts
pep/app/pods/components/modal-dialogs/user/about/template.hbs
pep/translations/en-us.json

Fixes #4 . Updates to about modal to provide status, and descriptions of PEP Web and PEP Archive.

Updates to about modal

---

pep/app/pods/components/drag-bar/component.ts
pep/app/pods/components/search/preview/component.ts
pep/app/pods/components/search/preview/template.hbs
pep/app/pods/search/controller.ts
pep/app/pods/search/route.ts
pep/app/styles/_variables.scss
pep/translations/en-us.json
pep/translations/es-es.json

Story/tp65873 Search left panel - round 3 (feedback)

---

pep/app/constants/configuration.ts
pep/app/pods/components/search/form/template.hbs

Story/tp65873 Search left panel - round 6 (help tooltips)

---

pep/app/authenticators/credentials.ts
pep/app/constants/search.ts

Fixing related docs search

---

pep/app/pods/components/page/sidebar/widgets/glossary-terms/component.ts

Fixing glossary card terms size when when only one result

---

.vscode/settings.json
pep/app/constants/sidebar.ts
pep/app/pods/most-cited/controller.ts
pep/app/pods/most-cited/nav/template.hbs
pep/app/pods/most-cited/route.ts
pep/app/pods/most-viewed/controller.ts
pep/app/pods/most-viewed/nav/template.hbs
pep/app/pods/most-viewed/route.ts
pep/app/pods/read/document/route.ts

Fixing filter names to pubperiod

---

pep/app/authenticators/credentials.ts
pep/app/authenticators/ip.ts
pep/app/pods/components/modal-dialogs/user/login/template.hbs
pep/translations/en-us.json

Login issue

---

pep/app/pods/application/footer/template.hbs
pep/app/pods/browse/book/gw/template.hbs
pep/app/pods/browse/book/se/template.hbs
pep/app/pods/browse/journal/index/template.hbs
pep/app/pods/browse/journal/volume/template.hbs
pep/app/pods/components/document/image/template.hbs
pep/app/pods/components/document/text/component.ts
pep/app/pods/components/image/component.ts
pep/app/pods/components/image/template.hbs
pep/app/pods/components/modal-dialogs/document/image/template.hbs
pep/public/xmlToHtml.xslt
pep/tests/integration/pods/components/image/component-test.ts

Adding session ID to images

---

pep/app/pods/components/modal-dialogs/user/preferences/component.ts
pep/app/pods/components/modal-dialogs/user/preferences/template.hbs

Fixing hic limit saving

---

pep/app/pods/browse/journal/index/route.ts

Change paging params

---

pep/app/pods/components/home/template.hbs
pep/app/styles/_pep-documents.scss

Show title again

---

pep/app/pods/application/adapter.ts
pep/app/pods/browse/journal/index/controller.ts
pep/app/pods/browse/journal/volume/controller.ts
pep/app/pods/most-cited-loading/route.ts
pep/app/pods/most-cited/controller.ts
pep/app/pods/most-viewed-loading/route.ts
pep/app/pods/read-loading/route.ts
pep/app/pods/read/document-loading/route.ts
pep/app/pods/read/document/controller.ts
pep/app/pods/read/document/route.ts
pep/app/pods/search/controller.ts
pep/app/pods/source-volume/adapter.ts
pep/app/pods/source/adapter.ts
pep/app/services/printer.ts
pep/app/services/row-selection.ts

Fixes ts errors and removing refine option changing until search hit

---

pep/app/pods/components/page/sidebar/widgets/whats-new/template.hbs

Linkify the whats new items

---

pep/app/pods/read/document/nav/template.hbs

Showing read later and favorites

---

pep/app/pods/search/controller.ts

Adding refine back

---

pep/app/pods/components/document/text/component.ts
pep/app/pods/components/modal-dialogs/user/info/component.ts
pep/app/pods/components/modal-dialogs/user/info/template.hbs
pep/app/pods/components/modal-dialogs/user/login/component.ts
pep/app/pods/components/page/nav/component.ts
pep/app/pods/components/page/nav/template.hbs
pep/tests/integration/pods/components/modal-dialogs/user/info/component-test.ts
pep/translations/en-us.json

added account info modal

---

pep/app/constants/configuration.ts
pep/app/pods/components/page/sidebar/widgets/publisher-info/template.hbs

added publisher info html

---

pep/app/pods/browse/journal/volume/controller.ts
pep/app/pods/browse/journal/volume/template.hbs

Handling items that dont have a issue number

---

pep/app/pods/components/home/component.ts
pep/app/pods/components/home/template.hbs
pep/app/styles/_utilities.scss
pep/translations/en-us.json

disassociated figure

---

pep/app/pods/components/search/item/bibliographic/component.ts
pep/app/pods/components/search/item/bibliographic/template.hbs

add document url href to article links

---

pep/app/pods/components/search/preview/component.ts
pep/app/pods/components/search/preview/template.hbs
pep/yarn.lock

Fixing resize to fit

---

pep/app/pods/read/document/route.ts

Fixing issue with search terms not saving

---

pep/app/constants/configuration.ts

Changing text on accolades card

---

pep/app/pods/search/read/controller.ts
pep/app/pods/search/read/route.ts
pep/app/pods/search/read/template.hbs
pep/public/xmlToHtml.xslt

Fixing #112 and #114

---

pep/app/pods/application/route.ts
pep/app/pods/browse/journal/volume/controller.ts
pep/app/pods/browse/journal/volume/template.hbs
pep/app/pods/browse/read/controller.ts
pep/app/pods/browse/read/route.ts
pep/app/pods/browse/read/template.hbs
pep/app/pods/components/search/preview/component.ts
pep/app/pods/components/search/preview/template.hbs
pep/app/pods/search/index/controller.ts
pep/app/pods/search/index/template.hbs
pep/app/pods/search/read/controller.ts
pep/app/router.js
pep/public/xmlToHtml.xslt

Fixing issues from read refactor that were missed

---

pep/app/constants/regex.ts
pep/app/pods/document/model.ts
pep/app/pods/search/read/route.ts

Fixing search fields

---

pep/app/constants/regex.ts
pep/app/pods/components/document/read/component.ts
pep/app/pods/components/document/read/template.hbs
pep/app/pods/components/document/search-hits/template.hbs
pep/app/pods/components/document/text/component.ts
pep/app/pods/components/page/sidebar/widgets/glossary-terms/component.ts
pep/app/pods/search/read/controller.ts
pep/app/pods/search/read/template.hbs
pep/app/styles/_utilities.scss
pep/public/xmlToHtml.xslt
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json

Fixes #256, #255, Part of #254, #239, #220
@nrshapiro in order to fully fix 254, I need more information. See https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/254#issuecomment-768350239

Multiple fixes

---

pep/app/authenticators/ip.ts
pep/app/pods/application/route.ts
pep/app/pods/application/template.hbs
pep/app/pods/components/information-bar/bars/settings-auth/component.ts
pep/app/pods/components/information-bar/bars/settings-auth/template.hbs
pep/app/pods/components/information-bar/component.ts
pep/app/pods/components/information-bar/message/component.ts
pep/app/pods/components/information-bar/message/template.hbs
pep/app/pods/components/information-bar/template.hbs
pep/app/pods/components/modal-dialogs/user/preferences/component.ts
pep/app/services/auth.ts
pep/app/services/current-user.ts
pep/app/services/information-bar.ts
pep/app/services/lang.ts
pep/app/services/theme.ts
pep/app/styles/_components.scss
pep/app/styles/_modal.scss
pep/app/styles/_variables-theme.scss
pep/app/styles/_variables.scss
pep/app/styles/components/_information-bar.scss
pep/app/utils/animation.ts
pep/app/utils/user.ts
pep/tests/integration/pods/components/information-bar/bars/settings-auth/component-test.ts
pep/tests/integration/pods/components/information-bar/component-test.ts
pep/tests/integration/pods/components/information-bar/message/component-test.ts
pep/tests/unit/services/information-bar-test.ts
pep/translations/en-us.json
pep/types/ember-animated/index.d.ts

login for IP when settings change

---

pep/app/pods/components/document/text/component.ts
pep/app/styles/components/read/document.scss
pep/public/xmlToHtml.xslt

Changing visuals when glossary term highlighting is off

---

pep/app/authenticators/credentials.ts
pep/app/authenticators/ip.ts
pep/types/ember-cli-fastboot/services/fastboot.d.ts

Adding in referrer header to IP call

---

pep/app/pods/search/index/controller.ts
pep/app/pods/search/index/route.ts

Adding user param to user preformed intial searches for logging

---

pep/app/pods/admin/language/route.ts
pep/app/pods/components/modal-dialogs/user/preferences/component.ts

Fixing out of sync widget issue

---

pep/app/pods/components/page/sidebar/widgets/favorites/component.ts
pep/app/pods/components/page/sidebar/widgets/favorites/template.hbs
pep/app/pods/components/page/sidebar/widgets/read-later/component.ts
pep/app/pods/components/page/sidebar/widgets/read-later/template.hbs
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json

Fixing label text

---

pep/app/pods/components/modal-dialogs/whats-new/subscription/template.hbs
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json

Remove IJP open

---

pep/app/authenticators/credentials.ts
pep/app/constants/cookies.ts
pep/app/constants/preferences.ts
pep/app/pods/application/route.ts
pep/app/pods/browser-data/controller.ts
pep/app/pods/components/page/sidebar/widgets/read-later/component.ts
pep/app/services/current-user.ts
pep/app/services/intro-tour.ts
pep/app/services/session.ts
pep/app/session-stores/application.js
pep/app/utils/user.ts
pep/tests/unit/services/intro-tour-test.ts

Fixing tour showing on logout

---

pep/app/pods/components/page/drawer/template.hbs
pep/app/pods/components/page/nav/template.hbs
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json

Add link to browser page

---

pep/app/constants/documents.ts
pep/app/pods/components/document/read/component.ts
pep/app/pods/components/document/text/component.ts
pep/app/pods/search/index/route.ts
pep/public/xmlToHtml.xslt

Fixing missing formatting links

---

pep/.ember-cli
pep/.gitignore
pep/app/constants/cookies.ts
pep/app/pods/application/adapter.ts
pep/app/pods/browse/journal/index/controller.ts
pep/app/pods/browse/journal/index/template.hbs
pep/app/session-stores/application.js
pep/package.json

Adding embargo changes

---

pep/app/constants/books.ts
pep/app/pods/browse/controller.ts
pep/app/pods/browse/nav/template.hbs
pep/app/utils/browse.ts

Remove dictionary from browse books page

---

pep/public/xmlToHtml.xslt

Fixing spacing issues

---

pep/app/pods/components/document/search-hits/component.ts
pep/public/xmlToHtml.xslt
pep/types/@gavant/ember-button-basic/component.d.ts
pep/types/ember-intl/helpers.d.ts

Adding abstract preview

---

pep/app/constants/regex.ts
pep/app/constants/search.ts
pep/app/pods/components/home/component.ts
pep/app/utils/search.ts
pep/types/pep/index.d.ts

Fixing syntax

---

pep/app/constants/configuration.ts
pep/app/pods/admin/general/template.hbs
pep/app/pods/components/page/drawer/component.ts
pep/app/pods/components/page/drawer/template.hbs
pep/app/pods/components/page/nav/component.ts
pep/app/pods/components/page/nav/template.hbs
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json
pep/types/@gavant/ember-bootstrap-dropdown/component.d.ts

Adding in new admin config for search video url

---

pep/app/pods/components/search/preview/component.ts
pep/app/pods/search/index/route.ts
pep/app/pods/search/read/route.ts

Fixing 404 issue

---

pep/app/pods/application/route.ts
pep/app/pods/components/alert/template.hbs
pep/app/pods/components/forms/login/template.hbs
pep/types/ember-animated/index.d.ts

Changes to llogin for group user and text location on sidebar

---

pep/public/xmlToHtml.xslt

Changes location of keywords - Fixes #433

Changing keyword location

---

pep/app/constants/configuration.ts
pep/app/constants/sidebar.ts
pep/app/pods/admin/general/template.hbs
pep/app/pods/browse/read/route.ts
pep/app/pods/components/page/sidebar/widgets/glossary-terms/component.ts
pep/app/pods/search/index/controller.ts
pep/app/pods/search/index/route.ts
pep/app/pods/search/read/route.ts
pep/translations/en-us.json
pep/tsconfig.json
pep/types/glint.d.ts
pep/types/global.d.ts
pep/types/pep/index.d.ts

Admin config for glossary terms limit

---

pep/app/constants/preferences.ts
pep/app/pods/application/controller.ts
pep/app/pods/components/document/read/component.ts
pep/app/pods/components/modal-dialogs/user/preferences/component.ts
pep/app/pods/components/modal-dialogs/user/preferences/template.hbs
pep/app/pods/search/index/controller.ts
pep/app/pods/search/index/route.ts
pep/app/utils/search.ts
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Fixing search form user settings user preferences

---

pep/app/pods/components/page/sidebar/right/template.hbs
pep/app/pods/components/page/sidebar/widgets/component.ts
pep/app/pods/components/page/sidebar/widgets/expert-picks/component.ts
pep/app/pods/components/page/sidebar/widgets/favorites/component.ts
pep/app/pods/components/page/sidebar/widgets/glossary-terms/component.ts
pep/app/pods/components/page/sidebar/widgets/more-like-these/component.ts
pep/app/pods/components/page/sidebar/widgets/most-cited/component.ts
pep/app/pods/components/page/sidebar/widgets/most-viewed/component.ts
pep/app/pods/components/page/sidebar/widgets/past-searches/component.ts
pep/app/pods/components/page/sidebar/widgets/publisher-info/component.ts
pep/app/pods/components/page/sidebar/widgets/read-later/component.ts
pep/app/pods/components/page/sidebar/widgets/related-documents/component.ts
pep/app/pods/components/page/sidebar/widgets/relevant-searches/component.ts
pep/app/pods/components/page/sidebar/widgets/seminal-papers/component.ts
pep/app/pods/components/page/sidebar/widgets/sign-in/component.ts
pep/app/pods/components/page/sidebar/widgets/topical-video-preview/component.ts
pep/app/pods/components/page/sidebar/widgets/video-preview/component.ts
pep/app/pods/components/page/sidebar/widgets/whats-new/component.ts
pep/app/pods/components/page/sidebar/widgets/your-interests/component.ts

Login changes to only show login panel if not authenticated

---

pep/app/pods/search/index/controller.ts
pep/app/utils/search.ts

Fixing clear issue

---

pep/app/styles/themes/dark.scss

Fixing dark theme select indictator color

---

pep/app/services/current-user.ts

Fixing close all

---

pep/app/pods/components/help-tooltip/component.ts
pep/app/pods/components/help-tooltip/template.hbs
pep/app/styles/components/_ember-tooltip.scss

Fixing tooltips

---

pep/app/pods/components/forms/login/component.ts
pep/app/pods/components/forms/login/template.hbs
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Login text changes

---

pep/app/pods/components/modal-dialogs/help/feedback/component.ts
pep/app/pods/components/modal-dialogs/help/feedback/template.hbs
pep/app/validations/help/feedback.ts
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

 Adding email to feedback modal

---

pep/app/pods/components/search/form/template.hbs
pep/app/styles/components/search/_form.scss

Fixing text in french

---

pep/app/constants/configuration.ts
pep/app/pods/admin/language/template.hbs
pep/app/pods/components/forms/login/template.hbs
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Adding admin login text control

---

.gitignore
pep/app/constants/configuration.ts
pep/app/pods/admin/general/template.hbs
pep/app/pods/admin/language/template.hbs
pep/app/pods/components/information-bar/bars/admin-message/component.ts
pep/app/pods/components/information-bar/bars/admin-message/template.hbs
pep/app/pods/components/scrollable/component.ts
pep/app/services/information-bar.ts
pep/app/services/scrollable.ts
pep/app/services/theme.ts
pep/app/templates/head.hbs
pep/node/lambda.js
pep/node/server.js
pep/tests/integration/pods/components/information-bar/bars/admin-message/component-test.ts
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Adding user disruption notification and fastboot timeout improvements

---

pep/app/pods/most-cited/controller.ts
pep/app/pods/most-viewed/controller.ts
pep/app/utils/url.ts

Adding session to most cited and most viewed calls

---

pep/app/constants/configuration.ts
pep/app/pods/admin/language/template.hbs
pep/app/pods/browse/read/template.hbs
pep/app/pods/components/document/actions/download/component.ts
pep/app/pods/components/document/actions/download/template.hbs
pep/app/pods/components/document/actions/print/component.ts
pep/app/pods/components/document/actions/print/template.hbs
pep/app/pods/components/search/preview/template.hbs
pep/app/pods/search/read/template.hbs
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Revised printing rules

---

pep/public/xmlToHtml.xslt

Adding / onto images to fix http redirect

---

pep/app/styles/components/read/document.scss
pep/public/xmlToHtml.xslt

Fixing video player display issue

---

pep/app/modifiers/did-value-update.ts
pep/app/pods/components/document/text/template.hbs

Fixing scroll issue

---

pep/app/constants/preferences.ts
pep/app/pods/browse/read/controller.ts
pep/app/pods/browse/read/template.hbs
pep/app/pods/components/disqus/comments/component.ts
pep/app/pods/components/draggable-container/component.ts
pep/app/pods/components/modal-dialogs/user/preferences/component.ts
pep/app/pods/components/modal-dialogs/user/preferences/template.hbs
pep/app/pods/search/read/controller.ts
pep/app/pods/search/read/template.hbs
pep/tests/integration/pods/components/draggable-container/component-test.ts
pep/translations/de-de.json
pep/translations/en-us.json
pep/translations/es-es.json
pep/translations/fr-fr.json
pep/translations/it-it.json

Adding comments into preferences

---

pep/app/pods/browse/read/controller.ts
pep/app/pods/browse/read/route.ts
pep/app/pods/search/read/controller.ts
pep/app/pods/search/read/route.ts

Fixing auth model refresh issue

---

pep/app/pods/components/page/sidebar/widgets/related-documents/component.ts

Use id instead

---

pep/app/constants/search.ts
pep/app/pods/components/page/sidebar/widgets/related-documents/component.ts
pep/app/pods/document/model.ts
pep/app/utils/search.ts
pep/app/utils/url.ts
pep/tests/unit/utils/search-test.ts

Fixing citation count facet change

---

pep/app/pods/browse/nav/template.hbs

Making field grow

---

pep/app/pods/browse/read/route.ts

Signed-off-by: Jordan Allen <jordan@jordanallen.org>

Remove model debugging

---

pep/app/pods/browse/read/template.hbs
pep/app/pods/search/read/template.hbs

Signed-off-by: Jordan Allen <jordan@jordanallen.org>

Use title instead of tooltip for comments

---

pep/public/xmlToHtml.xslt

Check for next pb in parent and current block scope

---

.github/workflows/video.yml
infra/video/bucket.tf
infra/video/cloudfront.tf
infra/video/dns.tf
infra/video/main.tf
infra/video/variables.tf
pep/app/constants/configuration.ts
pep/public/xmlToHtml.xslt

Cache video previews

---

pep/app/pods/admin/general/controller.ts

Hide video preview widgets when list in admin panel empty

---

pep/app/pods/application/route.ts

Reverts Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#788

Revert "Display PEP preview notice"
